### PR TITLE
Added Grammar Test Files for Validating Grammar Rules

### PR DESCRIPTION
**Pull request by kevinastone**
I recently wrote a package called [atom-grammar-test](https://www.npmjs.com/package/atom-grammar-test) that allows writing grammar tests inline in your example files.  Inspired by [ST3's Syntax Test](https://www.sublimetext.com/docs/3/syntax.html#Testing), it greatly helps writing complex cases since you're just annotating inline in your code examples.

I included two examples for JSX and Flowtype to showcase the usability.  It's much easier to write a regression in this grammar test format compared to either writing tests manually or relying on visual inspection.

### CODE REVIEW

**Comment by gandm** [comment]
Very nice. I saw ST3 had this feature and thought it was neat. I'll pull this when I get a chance. Thanks.

**Comment by gandm** [comment]
I got the following when running the specs. Looks like the regex check for the SYNTAX TEST is failing. 
image

image

**Comment by kevinastone** [comment]
Yeah, looks like a CRLF issue.  Let me add a test on my end and publish a new version.

**Comment by kevinastone** [comment]
@gandm added support for CRLF line endings in `atom-grammar-test` v0.1.2.  Can you npm install after updating this branch and try-again?

**Pull request merged**
