### PR TITLE
Adds grammar support for flow type annotations

### PR DESCRIPTION
**Pull request by rsms**
Includes:
- function argument types
- function return types
- arrow function arguments
- arrow function return types

screenshot 2015-08-01 19 10 09

> Note: Does not include type annotations for var declarations
> Note: The grammar file has been converted to cson

### CODE REVIEW

**Comment by gandm** [comment]
I've already done this I just haven't published t yet.

**Comment by gandm** [comment]
I have added support for class, class fields, var , let, cons, declare modules, declare type ,etc.

**Comment by rsms** [comment]
Oh, really? I tried your master branch and it seemed broken at best:

screenshot 2015-08-01 19 50 04

(^ cloned from gandm/language-babel@master just a minute ago)

**Comment by gandm** [comment]
It's just in my local repo at the moment. I have been testing it against a lot of files from react, babel, flowtype, etc. e.g.
image


I'm not planning to release it until next weekend as I'm tied up on other things at the moment.

**Comment by gandm** [comment]
Also, it's in a state of flux as I'm changing things in the grammar. Hence the errors in the above code that are showing now showing up that weren't a few hours ago!  I'm quite happy for someone to take over this project if they feel it would be worthwhile. I tend to think that nuclide will eventually support this in a better way than I can, so I doubt the package will last long!

**Comment by rsms** [comment]
Very cool. Nice work!
Looking forward to trashing by fork when you find some time to wrap up and publish your work.

**Comment by gandm** [comment]
Just published 0.11.0 with initial support for flow. This version doesn't support let, var and const typing. I can get it to work but only if I know where the  statement terminates. E.g. a semi-colon or a protected keyword, such as another var/if etc. However, there always seems to be an edge case that screws things, such as a global without a var keyword. The current grammar just isn't very good at this type of parsing.

I may support it if I can avoid the edge case issues.

**Comment by rsms** [comment]
Nice :)

**Pull request closed without merging**
