### PR TITLE
Looking for a new maintainer?

### PR DESCRIPTION
**Pull request by mgmcdermott**
Hey @gandm, I think this is a very important package in the react community. If you would like to pass this project on instead of not supporting it anymore, I would like to offer to maintain it. The only way I could get in contact with you is by opening a PR. Please contact me here or via email (michael@mgmcdermott.com) if you would consider letting me take over. Thank you.

### CODE REVIEW

**Comment by gandm** [comment]
Thanks for the offer but I think it would be prudent to leave things as they are. I will ensure that the current code runs on Atom1.13 but I won't be fixing any issues. Part of the reason for this is my understanding that the Facebook Nuclide team may well introduce a new grammar for flow, js, jsx that will be based upon vscode's new typescript grammar. If this does turn out to be true, then that will prove to be better solution long term. Also, I have found some of the comments in the issues raised rather curt and not terribly supportive. 

I'll close this for the time being and if things don't work out as I expect I will be happy to pass the code base over. Although I would advice against it. Looking at the star rating for the react package also gives me optimism that this would address most users needs.

**Comment by mgmcdermott** [comment]
Sounds good, thanks for all of your hard work on this.

**Comment by jonboiser** [comment]
Thank you @gandm. Your work on this package and keeping up with crazy JS syntax has been heroic. 💪 

I'm really interested in this news about a Facebook-supported nuclide/atom grammar. Where did you hear about this?

**Comment by gandm** [comment]
@jonboiser thanks for the kind words. I believe Andres Suarez is working on this but as with most things in life it may come to nothing. I believe it will be done first for Sublime Text and then Atom and VScode. see [his aims for the package](https://github.com/babel/babel-sublime/issues/293)

**Pull request closed without merging**
